services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: file_uploader
    ports:
      - "8001:8000"
    command:  python -m uvicorn file_uploader.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/opt/file_uploader
      - /home/ubuntu/.aws/:/root/.aws/:ro
      - /tmp/test:/tmp/test
    environment:
      POSTGRES_PORT: $DB_PORT
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PWD
      POSTGRES_HOST: $DB_HOST
      DJANGO_SETTINGS_MODULE: file_uploader.settings
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672/


  rabbitmq:
    image: rabbitmq:3.13.3-management
    command: sh -c "echo 'log.console.level = warning' >>/etc/rabbitmq/conf.d/10-default-guest-user.conf && rabbitmq-server"
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PORT: $DB_PORT
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PWD
    ports:
      - 5432:5432


  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: file_uploader
    depends_on:
      - rabbitmq
      - web
    command: celery -A file_uploader worker --concurrency=5 --loglevel=INFO
    ports:
      - 6900:6900
      - 6899:6899
    volumes:
      - .:/opt/file_uploader
      - /home/ubuntu/.aws/:/root/.aws/:ro
      - /tmp/test:/tmp/test
    environment:
      POSTGRES_PORT: $DB_PORT
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PWD
      POSTGRES_HOST: $DB_HOST
      DJANGO_SETTINGS_MODULE: file_uploader.settings
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672/