# Generated by Django 4.2.13 on 2024-06-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('object_name', models.CharField(max_length=255)),
                ('guid', models.CharField(max_length=255)),
                ('instance_uid', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.FloatField()),
            ],
        ),
    ]
