# Generated by Django 4.2.13 on 2024-06-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
